# Generated by Django 3.1.7 on 2021-03-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20210318_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
